# Generated by Django 2.2.5 on 2020-10-18 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculums', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.AddField(
            model_name='user',
            name='my_curriculums',
            field=models.ManyToManyField(blank=True, related_name='myC', to='curriculums.Curriculum'),
        ),
        migrations.AddField(
            model_name='user',
            name='saved_curriculum_titles',
            field=models.ManyToManyField(blank=True, related_name='savedC', to='curriculums.Curriculum'),
        ),
        migrations.AddField(
            model_name='user',
            name='subscribed_curriculum',
            field=models.ManyToManyField(blank=True, related_name='subscribedC', to='curriculums.Curriculum'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars'),
        ),
    ]
