# Generated by Django 2.2.5 on 2020-10-17 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculums', '0003_auto_20201016_2226'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.AddField(
            model_name='user',
            name='my_curriculums',
            field=models.ManyToManyField(blank=True, related_name='my', to='curriculums.Curriculum'),
        ),
        migrations.AddField(
            model_name='user',
            name='saved_curriculum_titles',
            field=models.ManyToManyField(blank=True, related_name='saved', to='curriculums.Curriculum'),
        ),
        migrations.AddField(
            model_name='user',
            name='subscribed_curriculum',
            field=models.ManyToManyField(blank=True, related_name='subscribed', to='curriculums.Curriculum'),
        ),
    ]
