# Generated by Django 2.2.5 on 2020-10-17 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201017_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='my_curriculums',
            field=models.ManyToManyField(blank=True, related_name='my', to='curriculums.Curriculum'),
        ),
        migrations.AlterField(
            model_name='user',
            name='saved_curriculum_titles',
            field=models.ManyToManyField(blank=True, related_name='saved', to='curriculums.Curriculum'),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscribed_curriculum',
            field=models.ManyToManyField(blank=True, related_name='subscribed', to='curriculums.Curriculum'),
        ),
    ]
