# Generated by Django 2.2.5 on 2020-10-18 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201017_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='my_curriculums',
            field=models.ManyToManyField(blank=True, related_name='myC', to='curriculums.Curriculum'),
        ),
        migrations.AlterField(
            model_name='user',
            name='saved_curriculum_titles',
            field=models.ManyToManyField(blank=True, related_name='savedC', to='curriculums.Curriculum'),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscribed_curriculum',
            field=models.ManyToManyField(blank=True, related_name='subscribedC', to='curriculums.Curriculum'),
        ),
    ]
