# Generated by Django 2.2.5 on 2020-11-18 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
    ]
