# Generated by Django 2.2.5 on 2020-11-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='related_skill',
            field=models.ManyToManyField(blank=True, to='curriculums.Skill'),
        ),
    ]
