# Generated by Django 2.2.5 on 2020-11-11 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculums', '0002_auto_20201106_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='budget',
            field=models.IntegerField(help_text='What is available budget?'),
        ),
    ]
