# Generated by Django 2.2.5 on 2020-11-06 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculums', '0002_auto_20201106_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='related_skill',
            field=models.ManyToManyField(blank=True, related_name='skill', to='curriculums.Skill'),
        ),
    ]
