# Generated by Django 2.2.5 on 2020-11-19 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculums', '0003_auto_20201111_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='education_background',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=30, null=True),
        ),
    ]
