# Generated by Django 2.2.5 on 2020-11-19 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculums', '0004_auto_20201118_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='education_background',
            field=models.CharField(choices=[('computer science', 'computer science'), ('STEM field', 'STEM field'), ('Non STEM field', 'Non STEM field')], max_length=30, null=True),
        ),
    ]
