# Generated by Django 3.1.3 on 2020-12-02 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculums', '0006_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='curriculum',
        ),
        migrations.AddField(
            model_name='curriculum',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task', to='curriculums.task'),
        ),
    ]
