# Generated by Django 3.1.3 on 2020-12-02 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculums', '0008_auto_20201202_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='curriculum',
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('curriculum', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day', to='curriculums.curriculum')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='task',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task', to='curriculums.day'),
        ),
    ]
