# Generated by Django 3.1.3 on 2020-12-02 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculums', '0009_auto_20201202_1239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task',
            new_name='day',
        ),
    ]
