# Generated by Django 3.1.3 on 2020-12-02 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculums', '0010_auto_20201202_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='day',
        ),
        migrations.DeleteModel(
            name='Day',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
