# Generated by Django 3.1.3 on 2020-12-06 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculums', '0012_day_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculum',
            name='created_date',
        ),
        migrations.AddField(
            model_name='curriculum',
            name='learning_goal',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('file', models.ImageField(upload_to='')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculums.curriculum')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
